set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'whatyouhide/vim-gotham'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" Defaults
colorscheme gotham
set number
set autoindent
set showmatch
set showmode
set colorcolumn=120
set encoding=utf-8
set tabstop=4 shiftwidth=4 expandtab
set mouse=a
if $COLORTERM == 'gnome-terminal'
    set t_Co=256
endif
" Keybindings
noremap <c-s-up> :call feedkeys( line('.')==1 ? '' : 'ddkP' )<CR>
noremap <c-s-down> ddp

" Visual indent
vnoremap <Tab> >
vnoremap <S-Tab> <
